language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
before_install: "pip install behave"
install: "pip install -r requirements.txt"
script: 
    - python setup.py test
    - python setup.py install
    - cd tests/behave && behave
